pipeline {
    agent any
    stages {
        stage('Build Auth') {
            steps {
                dir ('PetHouseBackend/auth') {
                   bat 'mvn clean package -DskipTests=true'
                }
            }
        }
        stage('Build Img Docker') {
            steps {
                script {
                    dir('PetHouseBackend/auth') {
                        bat 'docker build -t augustomello09/pethouse-backend-auth .'
                    }
                }        
            }
        }
        stage('Docker Push To DockerHub') {
            steps {
                script {
                    dir('PetHouseBackend/auth') {
                        bat 'docker login'
                        bat 'docker push augustomello09/pethouse-backend-auth:latest'
                    }
                }        
            }
        }
    }
} 