pipeline {
    agent any
    stages {
        stage('Build Auth') {
            steps {
                dir ('PetHouseBackend/auth') {
                   bat 'mvn clean package -DskipTests=true'
                }
            }
        }
    }
} 