stage('Build GatewayService') {
    steps {
        dir('PetHouseBackend/gateway') {
            bat 'mvn clean package -DskipTests=true'
        }
    }
}

stage('Build Img Docker') {
    steps {
        script {
            dir('PetHouseBackend/gateway') {
                bat 'docker build -t augustomello09/pethouse-backend-gateway .'
            }
        }
    }
} 