pipeline {
    agent any
    stages {
        stage('Build Gateway') {
            steps {
                dir ('PetHouseBackend/gateway') {
                   bat 'mvn clean package -DskipTests=true'
                }
            }
        }
    }
} 