server:
  port: 0

spring:
  jpa:
    open-in-view: true
  application:
    name: pethouse
  profiles:
    active:
    - test
  kafka:
    producer:
      bootstrap-servers: kafka:29092  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

auth:
  jwt:
    token:
      secret: 455a0595071af6e2385c0ec556cb329c
      
access:
  token: ${access_token}
  
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME} 
 
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
      
springdoc:
  show-actuator: true               