pipeline {
    agent any
	triggers {
		githubPush()
	}
    stages {
        stage('Build Pethouse') {
            steps {
                dir('PetHouseBackend/PetHouse') {
                    bat 'mvn clean package -DskipTests=true'
                }
            }
        }
        stage('JUnit Test') {
            steps {
                dir ('PetHouseBackend/PetHouse') {
                   bat 'mvn test'
                }
            }
        }
    }
}
