pipeline {
    agent any
    stages {
        stage('Build Payment') {
            steps {
                dir('PetHouseBackend/payment') {
                    bat 'mvn clean package -DskipTests=true'
                }
            }
        }
        stage('Build Img Docker') {
            steps {
                script {
                    dir('PetHouseBackend/payment') {
                        bat 'docker build -t augustomello09/pethouse-backend-payment .'
                    }
                }        
            }
        }
        stage('Docker Push To DockerHub') {
            steps {
                script {
                    dir('PetHouseBackend/payment') {
                        bat 'docker login'
                        bat 'docker push augustomello09/pethouse-backend-payment:latest'
                    }
                }        
            }
        }
    }
}
