server:
  port: 8081
spring:
  jpa:
    open-in-view: true
  application:
    name: PetHouse
  profiles:
    active:
    - test  

auth:
  jwt:
    token:
      secret: 455a0595071af6e2385c0ec556cb329c
      expiration: 2
    refresh-token:
      expiration: 8