pipeline {
    agent any
    stages {
        stage('Build Email') {
            steps {
                dir ('PetHouseBackend/email') {
                   bat 'mvn clean package -DskipTests=true'
                }
            }
        }
    }
} 