pipeline {
    agent any
    stages {
        stage('Build eureka') {
            when {
                changeset "PetHouseBackend/eureka/**"
            }
            steps {
                dir('PetHouseBackend/eureka') {
                    script {
                        if (fileExists('Jenkinsfile')) {
                            load 'Jenkinsfile'
                        }
                    }
                }
            }
        }
        stage('Build gateway') {
            when {
                changeset "PetHouseBackend/gateway/**"
            }
            steps {
                dir('PetHouseBackend/gateway') {
                    script {
                        if (fileExists('Jenkinsfile')) {
                            load 'Jenkinsfile'
                        }
                    }
                }
            }
        }
    }
}