pipeline {
    agent any
    stages {
        stage('Build Backend') {
            steps {
                dir ('PetHouseBackend') {
                   bat 'mvn clean package -DskipTests=true'
                }
            }
        }
        stage('JUnit Test') {
            steps {
                dir ('PetHouseBackend') {
                   bat 'mvn test'
                }
            }
        }
    }
}