spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pethouse-service  
          uri: lb://pethouse   
          predicates:
            - Path=/pethouse/**
        - id: auth-service  
          uri: lb://auth   
          predicates:
            - Path=/auth/**
        - id: payment-service  
          uri: lb://payment   
          predicates:
            - Path=/payment/**             

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
