spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pethouse-service  
          uri: lb://pethouse   
          predicates:
            - Path=/pethouse/**
        - id: auth-service  
          uri: lb://auth   
          predicates:
            - Path=/auth/**
        - id: payment-service  
          uri: lb://payment   
          predicates:
            - Path=/payment/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs                 

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
springdoc:
  show-actuator: true
  swagger-ui:
    urls:
      - name: pethouse
        url: /v3/api-docs/pethouse
      - name: auth
        url: /v3/api-docs/auth
      - name: payment
        url: /v3/api-docs/payment 
        
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans             
